var EarthBlocks =
{ "columns":9,
 "image":"EarthBlocks.png",
 "imageheight":264,
 "imagewidth":297,
 "margin":0,
 "name":"EarthBlocks",
 "spacing":1,
 "tilecount":72,
 "tiledversion":"1.9.2",
 "tileheight":32,
 "tiles":[
        {
         "id":9,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":1,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":10,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":11,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }],
 "tilewidth":32,
 "type":"tileset",
 "version":"1.9"
}