var EarthBlocks =
{ "columns":9,
 "image":"EarthBlocks.png",
 "imageheight":264,
 "imagewidth":297,
 "margin":0,
 "name":"EarthBlocks",
 "spacing":1,
 "tilecount":72,
 "tiledversion":"1.9.2",
 "tileheight":32,
 "tiles":[
        {
         "id":3,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32.0083791568473,
                     "id":2,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32.1759622937942,
                     "x":-0.335166273893689,
                     "y":1.11022302462516e-15
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "class":"BB",
         "id":9,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":2,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":1,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":10,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":11,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":12,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":false,
                     "width":32,
                     "x":0,
                     "y":0
                    }, 
                    {
                     "class":"",
                     "height":0,
                     "id":2,
                     "name":"",
                     "polygon":[
                            {
                             "x":0,
                             "y":0
                            }, 
                            {
                             "x":30.9211,
                             "y":-31.3158
                            }, 
                            {
                             "x":30.9211,
                             "y":0
                            }],
                     "rotation":0,
                     "visible":true,
                     "width":0,
                     "x":0.657895,
                     "y":31.5789
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":18,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":1,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":20,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":34,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":39,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":41,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":45,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":46,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":30,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":47,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":32,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":57,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":31,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":1,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":58,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":31,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":32,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":59,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":31,
                     "id":1,
                     "name":"",
                     "rotation":0,
                     "visible":true,
                     "width":31,
                     "x":0,
                     "y":0
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }],
 "tilewidth":32,
 "type":"tileset",
 "version":"1.9"
}