var Healthpack =
{ "columns":2,
 "image":"Healthpack.png",
 "imageheight":32,
 "imagewidth":64,
 "margin":0,
 "name":"Healthpack",
 "spacing":0,
 "tilecount":8,
 "tiledversion":"1.9.2",
 "tileheight":32,
 "tiles":[
        {
         "id":0,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":21,
                     "id":1,
                     "name":"HealthPack",
                     "rotation":0,
                     "visible":true,
                     "width":25,
                     "x":7,
                     "y":7
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }, 
        {
         "id":1,
         "objectgroup":
            {
             "draworder":"index",
             "id":2,
             "name":"",
             "objects":[
                    {
                     "class":"BB",
                     "height":21,
                     "id":1,
                     "name":"HealthPack",
                     "rotation":0,
                     "visible":true,
                     "width":27,
                     "x":0,
                     "y":7
                    }],
             "opacity":1,
             "type":"objectgroup",
             "visible":true,
             "x":0,
             "y":0
            }
        }],
 "tilewidth":32,
 "transformations":
    {
     "hflip":true,
     "preferuntransformed":false,
     "rotate":false,
     "vflip":false
    },
 "type":"tileset",
 "version":"1.9"
}